### ISSUE TITLE
ERROR CODE -NAME

### ISSUE THREAD

**Issue by KarenStewart** [nateprat/GCU_Integrated_Project_Money_Saver_Application#41]
AS A user
I WANT TO know when I have entered the incorrect data field in 'Name'
SO THAT I can enter the correct data value

GIVEN I input other data values; number & special characters
WHEN I enter an unacceptable character
THEN an error message will be presented on screen informing me that I have entered the wrong field and be asked to enter number or special character values

**Comment by nateprat** [comment]
Error codes have been changed to not letting the user putting incorrect fields by restricting what can be entered

**Comment by nateprat** [comment]
Error notifications have been added so that if by an internal error occurs while adding the transaction. It will notify the user of the failed transaction.
